### ISSUE TITLE
Issue with node-sass package: Linux 64-bit with false

### ISSUE THREAD

**Issue by ruslanguns** [CeliaRozalenM/angular-katas#14]
I was unable to run the apps because `node-sass` package was struggling with an issue with my 64bit unix system (under WSL), the way I fixed it, was by simply reinstalling this package.

I will send you a PR with the fix. However it will add a node-sass as an explicit dependency.

**Solution:**
- `npm uninstall node-sass && npm install node-sass`

**Related issue to:**
- https://github.com/sass/node-sass/issues/1651

**Referenced comment:** 
- https://github.com/sass/node-sass/issues/1651#issuecomment-237525957

**Sample of the error:**

```bash
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.12.0
    at module.exports (/home/ruslan/aveva/angular-katas/calculator/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/ruslan/aveva/angular-katas/calculator/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.sassLoader (/home/ruslan/aveva/angular-katas/calculator/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/calculator/calculator.component.sass
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.12.0
    at module.exports (/home/ruslan/aveva/angular-katas/calculator/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/ruslan/aveva/angular-katas/calculator/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.sassLoader (/home/ruslan/aveva/angular-katas/calculator/node_modules/sass-loader/lib/loader.js:46:72)
```

**Comment by CeliaRozalenM** [comment]
Thanks, @ruslanguns for finding the issue and providing the pull request! 😀
